{
  lib,
  flake-parts-lib,
  neovim-lib,
  ...
}: let
  inherit (lib) concatStringsSep filterAttrs mapAttrsToList mkOption;
  inherit (flake-parts-lib) mkPerSystemOption;
  inherit (neovim-lib) mkLuaOption toLua;
in {
  options = {
    perSystem = mkPerSystemOption ({
      config,
      pkgs,
      ...
    }: {
      options = with lib.types; {
        neovim.build = {
          globals = mkOption {
            internal = true;
            type = package;
          };
        };

        # TODO: Generate these.
        vim.g = {
          do_filetype_lua = mkLuaOption bool;
          loaded_2html_plugin = mkLuaOption bool;
          loaded_getscript = mkLuaOption bool;
          loaded_getscriptPlugin = mkLuaOption bool;
          loaded_gzip = mkLuaOption bool;
          loaded_logiPat = mkLuaOption bool;
          loaded_matchit = mkLuaOption bool;
          loaded_matchparen = mkLuaOption bool;
          loaded_netrw = mkLuaOption bool;
          loaded_netrwPlugin = mkLuaOption bool;
          loaded_netrwSettings = mkLuaOption bool;
          loaded_rrhelper = mkLuaOption bool;
          loaded_tar = mkLuaOption bool;
          loaded_tarPlugin = mkLuaOption bool;
          loaded_vimball = mkLuaOption bool;
          loaded_vimballPlugin = mkLuaOption bool;
          loaded_zip = mkLuaOption bool;
          loaded_zipPlugin = mkLuaOption bool;
          mapleader = mkLuaOption str;
        };
      };

      config = {
        neovim.build.globals = let
          opts =
            mapAttrsToList (
              name: value: ''
                vim.g.${name} = ${toLua value}
              ''
            )
            (filterAttrs (_: value: value != null) config.vim.g);
        in
          pkgs.writeTextFile {
            name = "globals.lua";
            text =
              ''
                -- Generated by Nix (via github:willruggiano/neovim.nix)
              ''
              + (concatStringsSep "\n" opts);
          };
      };
    });
  };
}
