name: Update, build and test example flake

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  update-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v25
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix flake lock --update-input neovim-nix ./example
      - run: nix run .#check
      - run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'willruggiano@users.noreply.github.com'
          git commit -am 'chore: update example' || exit 0
          git push
